### ISSUE TITLE
Main.o missing? 

### ISSUE THREAD

**Issue by ghost** [Rinnegatamante/uo_amphetamin#1]
I tried compiling it with my Ubuntu 16.04 VM and the output of "make" was that Main.o was missing. How can i fix it?

**Comment by BeatPlay** [comment]
directly found a fix... sorry for posting!

 In the makefile there are 3 typos, i just changed "OBJS = main.o blit.o font.o" to "OBJS = main.c blit.c font.c" and it worked

**Comment by Rinnegatamante** [comment]
Never had such issue when actually compiling.

**Comment by ghost** [comment]
kinda worked around it! Used a real machine (not VM) to run Ubuntu and it worked perfekt!
i think my VM is just damaged...
